name: Fetch Google Sheets Value

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour

jobs:
  fetch-sheet-value:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Fetch value from Google Sheets
        env:
          SHEET_ID: ${{ secrets.CAFFEINE_SHEET_ID }}
          API_KEY: ${{ secrets.SHEET_API_KEY }}
        run: |
          mkdir -p data  # Ensure data directory exists

          # Specify the range you want to fetch
          RANGE="Sheet1!A1"
          RESPONSE=$(curl -s "https://sheets.googleapis.com/v4/spreadsheets/${SHEET_ID}/values/${RANGE}?key=${API_KEY}")
          
          # Extract the cell value from the JSON response
          VALUE=$(echo "$RESPONSE" | jq -r '.values[0][0]')
          
          # Check if the value is different to avoid unnecessary commits
          if [[ -f data/sheet_value.json && "$(jq -r '.sheetValue' data/sheet_value.json)" == "$VALUE" ]]; then
            echo "No changes in sheet value. Skipping commit."
            exit 0
          fi

          # Update JSON file if value has changed
          echo "{\"sheetValue\": \"$VALUE\"}" > data/sheet_value.json

      - name: Commit and push changes
        if: success()  # Only runs if previous step didn't exit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data/sheet_value.json
          
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update sheet value"
            git pull --rebase origin main            
            git push
          fi
      
      #- name: Trigger GitHub Pages rebuild
        #if#: success()  # Only run if there was a commit and push
        #env:
          #USER_TOKEN: $#{{ secrets.USER_TOKEN }}
        #run: |
          #curl --fail --request POST \
            #--url https://api.github.com/repos/$#{{ github.repository }}/pages/builds \
            #--header "Authorization: Bearer $USER_TOKEN"
