name: Update Google Sheets Secrets

on:
  push:
    branches:
      - main

jobs:
  update-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Insert Secrets into JavaScript
        env:
          SHEET_ID: ${{ secrets.CAFFEINE_SHEET_ID }}
          API_KEY: ${{ secrets.SHEET_API_KEY }}
        run: |
          echo "const sheetID = '${SHEET_ID}'; const apiKey = '${API_KEY}';" > secrets.js

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add secrets.js
          git commit -m "Add Google Sheets secrets"
          git push
